127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
192.168.0.35    pratice.adeolagroup.com
192.168.0.125   nginx.adeolagroup.com
192.168.0.30    tower.adeolagroup.com
192.168.0.115   rhce.adeolagroup.com
192.168.0.105   nifi1.adeolagroup.com
192.168.0.101   nifi2.adeolagroup.com
192.168.0.110   nifi3.adeolagroup.com
192.168.0.130   lab.adeolagroup.com
192.168.0.128   grafana.adeolagroup.com
192.168.0.126   jenkins.adeolagroup.com
192.168.0.123   gocd.adeolagroup.com
192.168.0.121   apache.adeolagroup.com
