---
- name: playbook to ping hosts
  hosts: all
  become: yes
  remote_user: root

  tasks:
    - name: clean up the repos
      shell: yum clean all
      args:
        warn: no

    - name: repolist the repos
      shell: yum repolist all
      warn: False

    - name: update the server
      shell: yum update
      warn: False

    - name: reboot the hosts
      shell: shutdow -r now