---
- name: playbook to ping hosts
  hosts: all
  become: yes
  remote_user: root

  tasks:
    - name: clean up the repos
      shell: yum clean all
      args:
        warn: no

    - name: repolist the repos
      shell: yum repolist all
#      warn: False

#    - name: update the server
#      shell: yum update

    - name: update the package
      yum:
        name: '*'
        state: latest

    - name: reboot the server
      shell: "sleep 5 && shutdown -r now"

    - name: wait for the system to reboot
      wait_for _connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300