---
#playbook to manage my service
- hosts: "{{ hosts_inventory }}"
  become: yes
- name: playbook for looping over service
  vars:
    service: "{{ service_name }}"
  tasks: 
    - name: looping over service
      include_tasks: service-management.yml
      with_items:
        - "{{ service }}"
      loop_control:
        loop_var: service